### ISSUE TITLE
Telegram Number Banned when loading From saved session

### ISSUE THREAD

**Issue by Thankgod20** [gotd/td#1042]
I need urgent help here. When Authorising a client from saved session in Json file, once the authorisation is complete, telegram bans the client phone number. Whats the reason for this.

**Comment by ernado** [comment]
Please ask telegram.

Everyting related to bans: https://github.com/gotd/td/blob/main/.github/SUPPORT.md#how-to-not-get-banned

I'm getting banned on telethon and gotd in same proportion on fresh accounts, so it is not gotd-related problem.
