### ISSUE TITLE
subject: user not found when reply message

### ISSUE THREAD

**Issue by procolost** [gotd/td#1048]
### What version of gotd are you using?

```bash
$ go list -m github.com/gotd/td
```
```
github.com/gotd/td v0.79.1-0.20230412085615-17bf557db5c6
```
### Can this issue be reproduced with the latest version?

Yes
### What did you do?

[code](https://gist.github.com/procolost/e4651c1cdcd859e776521e117c0781b1)
start as user bot 
send user bot ping
### What did you expect to see?
rep message pong 
### What did you see instead?
err  [raise error](https://github.com/gotd/td/blob/17bf557db5c6877d6843d7f064f929a259af4333/telegram/message/peer/extract.go#L110)
### What Go version and environment are you using?

```bash
1.20.3 amd64
```

<details>
    <summary>
        <code>go env</code> Output
    </summary>
    <br />
    <pre>$ go env</pre>
</details>

**Comment by ernado** [comment]
https://github.com/gotd/td/issues/632#issuecomment-1466445837
