### ISSUE TITLE
MessagesGetAllChats was removed by Telegram

### ISSUE THREAD

**Issue by gpyun** [gotd/td#1071]
**What version of gotd are you using?**
github.com/gotd/td v0.80.0

**Can this issue be reproduced with the latest version?**
Yes

**What did you do?**
```
Tg, T := tgclient.API().MessagesGetAllChats(cg.Request.Context(), []int64{})
if T != nil {
	return T.Error(), Tg
}
```

**What did you expect to see?**
No error

 **What did you see instead?**
rpcDoRequest: rpc error code 400: INPUT_METHOD_INVALID (869209)

**What Go version and environment are you using?**
go1.19rc1 windows_amd64

**Comment by ernado** [comment]
https://t.me/tdlibchat/71168


> The method has never been used by official apps and is useless for real apps. It was removed.

@levlam

**Comment by ernado** [comment]
Probably GetDialogs or something like that, I'm not sure, sorry.

**Comment by injuryzy** [comment]
请问一下现在怎样获取所有的聊天频道呢

**Comment by injuryzy** [comment]
> 这个可以 thank you
