### ISSUE TITLE
INPUT_METHOD_INVALID while trying to tgClient.API().MessagesGetAllChats(ctx, exceptIds)

### ISSUE THREAD

**Issue by CeSiumUA** [gotd/td#1077]
### What version of gotd are you using?
latest available (v0.81.0)

### Can this issue be reproduced with the latest version?
Yes

### What did you do?
Calling `tgClient.API().MessagesGetAllChats(ctx, exceptIds)`

### What did you expect to see?
All my chats (without any errors, at least :) )

### What did you see instead?
error is returned, with such message:
`rpcDoRequest: rpc error code 400: INPUT_METHOD_INVALID (271630)`

### What Go version and environment are you using?
`go version go1.20.3 windows/amd64`

**Comment by ernado** [comment]
#1071

**Comment by CeSiumUA** [comment]
Got it, thank you very much for fast reply :)
