### ISSUE TITLE
how to get the sender's information from MessagesChannelMessages?

### ISSUE THREAD

**Issue by scp-66** [gotd/td#1117]
### Discussed in https://github.com/gotd/td/discussions/1116

<div type='discussions-op-text'>

<sup>Originally posted by **scp-66** June  8, 2023</sup>
Hello, thank you very much for your development, this library has greatly facilitated my work. I apologize that I am still a beginner with the Telegram API. When I use this library to get the message history of a channel, I can only find their FromID.UserID. I have tried for a long time, but I couldn't find a graceful way to associate this UserID with the sender's information, such as their username, and display it. Can you teach me how?</div>

**Comment by sky7987** [comment]
> I have already solved it.

How to do it
