### ISSUE TITLE
Get sender information

### ISSUE THREAD

**Issue by voyager-hang** [gotd/td#1130]
### Description
Hello, I'm sorry to bother you again, but I would like to ask you how to obtain the information of the sender when receiving a message, when it is not a contact person. tg.Entities is printed but it seems to be empty

**Comment by voyager-hang** [comment]
UsersGetFullUser

**Comment by ImanAski** [comment]
It still won't get the user if the user is not a contact.

**Comment by ImanAski** [comment]
`func FetchFullUserById(ctx context.Context, client *telegram.Client, userId int64) (*tg.UserFull, error) {
	userFull, err := client.API().UsersGetFullUser(ctx, &tg.InputUser{
		UserID: userId,
	})
	if err != nil {
		return nil, err
	}
	return &userFull.FullUser, nil
}`

I will pass the update message peer id as the userId.
