### ISSUE TITLE
mtproto: expose packages under the `internal` dir

### ISSUE THREAD

**Issue by iyear** [gotd/td#1321]
Can you expose packages(like crypto, exchange, mtproto, etc.) under the internal directory so that I can perform some low-level operations and debugging on MTProto?

They are all well-designed and implemented. I believe they can be exposed as packages for general purposes for external use.

**Comment by ernado** [comment]
Will do

**Comment by ernado** [comment]
Please try `v0.98.0`

**Comment by iyear** [comment]
Thanks! LGTM
