### ISSUE TITLE
bug: replyheader is always nil in `UpdateNewMessage`

### ISSUE THREAD

**Issue by sadfun** [gotd/td#1338]
### What version of gotd are you using?

```bash
github.com/gotd/td v0.96.0
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Receiving `UpdateNewMessage` using `td/telegram/updates`

### What did you expect to see?

`message.ReplyTo.(*tg.MessageReplyHeader)` reflects information about which message this is a response to.

### What did you see instead?

`message.ReplyTo.(*tg.MessageReplyHeader)` is always `nil`, even when message is a reply to something.

### What Go version and environment are you using?

```bash
go version go1.21.1 darwin/arm64 (reproduced in x86 arch too)
```

**Comment by refaldyrk** [comment]
Hello, are u got banned from telegram?

**Comment by NikBuka** [comment]
Hello @ernado, we have this problem too, plese fix this

**Comment by ernado** [comment]
I will try to fix it as soon as possible. 

Also any help is appreciated.

**Comment by ernado** [comment]
For some reason telegram just don't send this header. Flag `#3` is not set and reply_to:flags.3?[MessageReplyHeader](https://core.telegram.org/type/MessageReplyHeader) part of Message schema describes flag number 3 is `ReployTo` field.

Not sure what I can do there. How other libraries handle this?

**Comment by ernado** [comment]
Telegram is actually sending those.

Bug is in ShortMessage to Message conventer.

**Comment by NikBuka** [comment]
@ernado  thank you very much!

**Comment by ernado** [comment]
Thank you for reporting this bug! Please try `v0.99.2`.
