### ISSUE TITLE
assignment mismatch: 1 variable but snap.NewIter returns 2 values

### ISSUE THREAD

**Issue by TNT-ma** [gotd/td#1364]
\contrib@v0.19.0\pebble\peer_storage.go:99:10: assignment mismatch: 1 variable but snap.NewIter returns 2 values

**Comment by ernado** [comment]
```bash
go get github.com/gotd/contrib@v0.20.0
go get github.com/cockroachdb/pebble@v1.1.0
```

**Comment by ernado** [comment]
I've released https://github.com/gotd/contrib/releases/tag/v0.20.0
Should be ok now
