### ISSUE TITLE
gen: improve camel case to pascal

### ISSUE THREAD

**Issue by ernado** [gotd/td#143]
Upper version of `cdnConfig` should be `CDNConfig`, not `CdnConfig`.

In general, snake to pascal/camel is good, but lower camel to upper camel is bad.
Probably we should split words by upper case, like `fooBarBaz` to `foo Bar Baz`.

**Comment by 96RadhikaJadhav** [comment]
@ernado  Can I work on it?

**Comment by ernado** [comment]
Yes! 
Use https://github.com/gotd/td/blob/main/internal/gen/names.go as starting point
