### ISSUE TITLE
Account Banned

### ISSUE THREAD

**Issue by asadbekGo** [gotd/td#1470]
I created a session, made a login and send a message to another user. Everything works. When I re-launch the program, my number is blocked by telegram, i.e. my number was banned. Has anyone encountered such a problem?

**Comment by ernado** [comment]
I've encountered this issue myself several times on new accounts.
Sometimes it works, sometimes not.

Being very passive at start and not performing even readonly requests usually helps.

Also a dup of #1138.

Unfortunally I don't know how to help here more.
Very sorry you've got banned.
