### ISSUE TITLE
gen: use errors.Is instead of type assertation

### ISSUE THREAD

**Issue by tdakkota** [gotd/td#190]
From https://t.me/gotd_ru/29103.

We should use `errors.Is` here instead of type assert.
https://github.com/gotd/td/blob/8d82d61b16e7ea87af025712f1fdfa6a4117dcd9/internal/gen/_template/errors.tmpl#L16-L19

**Comment by ernado** [comment]
Fixed in 7bd207396e89601f0b15d186da05d064120bcfc4 via using separate package.

Now we have `tgerr` package for errors that is used both in generated and client code.
