### ISSUE TITLE
client: use WithContext pattern

### ISSUE THREAD

**Issue by tie** [gotd/td#221]
Currently using `telegram.Client` requires passing `context.Context` to almost all method invocations. However, in most cases we just use the context passed to `Run` “callback” function.

We can make the use of context optional and default to background context using the `WithContext` pattern.

__Before__

```go
err := client.Run(context.Background(), func(ctx context.Context) error {
	if err := client.AuthIfNecessary(ctx, authFlow); err ≠ nil {
		return err
	}
	self, err := client.Self(ctx)
	if err ≠ nil {
		return err
	}
	fmt.Println(self)
	return nil
})
```

__After__ (context-free)

```go
err := client.Run(func(client *telegram.Client) error {
	if err := client.AuthIfNecessary(authFlow); err ≠ nil {
		return err
	}
	self, err := client.Self()
	if err ≠ nil {
		return err
	}
	fmt.Println(self)
	return nil
})
```

__After__ (using context)

```go
ctx := req.Context()
ctx, cancel := context.WithCancel(ctx)
err := client.WithContext(ctx).Run(func(client *telegram.Client) error {
	if err := client.AuthIfNecessary(authFlow); err ≠ nil {
		return err
	}
	self, err := client.Self()
	if err ≠ nil {
		return err
	}
	return doSomething(client.Context(), self)
})
```

**Comment by tdakkota** [comment]
Context is used to control the lifetime of request, connection or client. Also we can use it pass different values to trace request execution (see #172).

Request lifetime may be is not equal to client lifetime, so I see no reason why methods client methods should not have `context.Context` parameter.

**Comment by tie** [comment]
Indeed, but this proposal doesn’t prevent you from passing context per request, e.g.

```go
client.WithContext(ctx).Self()
```

Usually you’d do a series of operations with *single* context, on *one* client. So passing `ctx` each time seems redundant.

**Comment by tdakkota** [comment]
> ```go
> client.WithContext(ctx).Self()
> ```

Where is context of request should be stored?

**Comment by tie** [comment]
Besides, currently the only context we can reasonably pass to the client is the one in `func(ctx context.Client) error` callback. And anything other than that would require some non-trivial hacks to merge *at least* callback context cancellation with user’s context.

**Comment by tie** [comment]
>Where is context of request should be stored

Just to be clear, `WithContext` pattern usually assumes shallow copies of the object context is attached to.
That is, a possible implementation would have
- an internal `*baseClient` that implements context-based APIs,
- and a public `*Client` that invokes methods on internal client using the attached context.

**Comment by tdakkota** [comment]
> > Where is context of request should be stored
> 
> Just to be clear, `WithContext` pattern usually assumes shallow copies of the object context is attached to.
> That is, a possible implementation would have
> 
> * an internal `*baseClient` that implements context-based APIs,
> * and a public `*Client` that invokes methods on internal client using the attached context.

If you want API without `context.Context`, so you can add your own builder.

I see no reason why `gotd`  should provide this functionality. `WithContext` is not a pattern, I don't know any project which uses it. 

The `*baseClient`/`Client`  separation produces API duplication, you must to not forget to add the same method to two different structures.

**Comment by ernado** [comment]
https://blog.golang.org/context-and-structs

> Contexts should not be stored inside a struct type, but instead passed to each function that needs it.

**Comment by tie** [comment]
Thanks for consideration! I understand your point, though I don’t agree that it’s a strict rule, and telegram.Client looks like a potential exception to me. It’s not a critical issue though, so I’m fine with closing this.
