### ISSUE TITLE
sign in with password: check password: rpcDoRequest: rpc error code 400: PASSWORD_HASH_INVALID

### ISSUE THREAD

**Issue by williamleecn** [gotd/td#253]
2FA password input was correct, but request return error

**Comment by ernado** [comment]
Hi, thank you for report!

Most likely you are passing wrong password. Can you please share code snipped that you are using?

Probably you are not trimming space characters, you can try `strings.TrimSpace(password)`.

**Comment by williamleecn** [comment]
It's okay now, get the password from stdin need trim \n
