### ISSUE TITLE
Testing package: Add a helper package to aid writing tests

### ISSUE THREAD

**Issue by aluxian** [gotd/td#294]
### Description

Currently, it's hard to write tests that use telegram.Client because there's no way to get access to an rpc mock (it's internal).

I propose adding a new package, e.g. `telegramtest`. If [mockClient](https://github.com/gotd/td/blob/2c06645b60a0ef76508d1017addfb8e611f102e1/telegram/client_test.go#L88) were public, I believe it would be enough for me to start writing my own tests for my project.

### References

Uber's [zap](https://github.com/uber-go/zap) has both a `zap` package and a `zaptest` one with helpers.

**Comment by aluxian** [comment]
I'd also welcome any existing solutions.

So far I've managed to write mocked tests that use `tg.Client` because I can easily create my own invoker. But I haven't found a way to pass a custom invoker to `telegram.Client`.

P.S. Thank you for creating this library, it's absolutely amazing the amount of work you've put in to maintain it. It's reliable and a lot lot lot better than the alternatives.

**Comment by aluxian** [comment]
If my proposal is the right way to go I'm happy to submit a draft PR.

**Comment by ernado** [comment]
Great idea, 100% agree, PR is very welcome!

Also there is a very simple server for e2e tests (also internal), can be useful while implementing PR (probably only as a reference).

**Comment by ernado** [comment]
Also feel free to ask anything in our telegram dev channel.

**Comment by aluxian** [comment]
Thanks @ernado, I'll join the Telegram dev channel and give this a try next week, cheers!

**Comment by aluxian** [comment]
Update: I decided to write more end to end tests using the staging server as those would be more reliable for my project.

I probably won't get to write the test package I proposed any time soon, so I'm leaving this issue up for grabs.

**Comment by ernado** [comment]
Got it.

We will eventually grab this issue and provide a testing package, thank you.

**Comment by aluxian** [comment]
Thanks for understanding and again huge thanks for building this, once my project has revenue I will definitely be contributing back.
