### ISSUE TITLE
BUG: maxMessageSize too small for method upload.getFile

### ISSUE THREAD

**Issue by Doflatango** [gotd/td#412]
Related telegram documentations:
* [upload.getFile](https://core.telegram.org/method/upload.getFile)
* [Downloading files](https://core.telegram.org/api/files#downloading-files)

The parameter `limit` in method `upload.getFile` can up to 1048576 (1 MB), this method can return more than 1048576 bytes messages, which will cause an `invalidMsgLenErr` error.

https://github.com/gotd/td/blob/fc0102aac09403b6c814f0189aaa781b29af7912/internal/proto/codec/errors.go#L36

**Comment by ernado** [comment]
Thank you! This should be fixed now.

Please try `v0.45.1`:

```console
$ go get github.com/gotd/td@v0.45.1
```

Looks like ~1.5mb should be more that enough.
Feel free to reopen if problem is not fixed.

**Comment by Doflatango** [comment]
@ernado It fixed now! Thank you!
