### ISSUE TITLE
[SUBJECT]: [DESCRIPTION]

### ISSUE THREAD

**Issue by AsuraTS** [gotd/td#553]
It would be great to add a method like WithRange(startOffset, endOffset) or WithRange(offset, totalLimit) to the downloader, or some other way to specify downloading chunks, and get part of the file.
This need for to work with http range requests, for example, in the case of file proxying via the web.

**Comment by ernado** [comment]
Hi, please take a look at https://github.com/gotd/contrib/tree/master/http_range

**Comment by ernado** [comment]
https://github.com/gotd/contrib/blob/master/tg_io/download.go

**Comment by ernado** [comment]
Oops, wrong link again.

Correct: https://pkg.go.dev/github.com/gotd/contrib@v0.11.0/http_io

This is already implemented in contrib.
