### ISSUE TITLE
updates: First update is dropped

### ISSUE THREAD

**Issue by MeanSquaredError** [gotd/td#671]
### What version of gotd are you using?

github.com/gotd/td v0.55.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I created a Telegram channel and joined that channel.
Then I ran a slightly modified version of examples/updates-gap-recover/ which connects to a Telegram server and logs all tg.UpdateNewChannelMessage events.
Then I started posting messages in the channel

### What did you expect to see?

I expected it to log all the messages in the channel that were received after the program connected to the Telegram server.

### What did you see instead?

It was dropping the first message and logging all the messages starting from the second one sent after the program connected to the Telegram server. The same problem shows up with other channels which I did not create myself. However with my own channel the problem is much easier to reproduce because I can post messages in that channel and don't have to wait for the new messages.

### What Go version and environment are you using?

go version go1.17 linux/amd64

Essentially the problem is caused by the fact that if there is a message for a new channel for which there is still no state then
`github.com/gotd/td/telegram/updates.(*state).handleChannel()` will create a new state and will try to deduce `localPts` value from that first message for the channel.

For whatever reason the Telegram server sends the first couple of messages out of order. Normally if `localPts` is already initializes then gotd will resolve the gap by waiting. However in my case the first couple of messages always look like this:

```
(dlv) p u.Updates
[]github.com/gotd/td/tg.UpdateClass len: 2, cap: 2, [
        *github.com/gotd/td/tg.UpdateReadChannelInbox {Flags: 0, FolderID: 0, ChannelID: XXXXXXXXXX, MaxID: 25, StillUnreadCount: 0, Pts: 26},
        *github.com/gotd/td/tg.UpdateNewChannelMessage {
                Message: github.com/gotd/td/tg.MessageClass(*github.com/gotd/td/tg.Message) ...,
                Pts: 26,
                PtsCount: 1,},
]
```

Then what happens is that gotd sees the first message `UpdateReadChannelInbox`. It has pts=26 and gotd correctly assumes that pts_count=0
localPts is set to pts-pts_count = 26 - 0 = 26

Then gotd starts processing the next message (`UpdateNewChannelMessage`) and sees that it has pts=26, pts_count=1, so gotd expects localPts=pts-pts_count=25, but localPts is already initialized to 26 by the previous UpdateReadChannelInbox which was received out-of-order. Therefore
`updates.(*sequenceBox).Handle(u update)` says `Outdated update, skip` and the message is effectively dropped.

This problem happens with any channel and I am not sure how exactly to fix it. I guess the easiest approach would be to read the `pts` from the server and then initialize localPts accordingly before actually handling updates from the server. Maybe the updates package could be fixed or the example in updates-gap-recover could be extended to initialize localPts.

**Comment by tdakkota** [comment]
I've created [`v0.55.2-pre`](https://github.com/gotd/td/releases/tag/v0.55.2-pre) release. Can you check it?

Thank you for bug report and for investigation. It is very helpful for us.

**Comment by MeanSquaredError** [comment]
I checked v0.55.2-pre and I can confirm that the new version works correctly and the first message is never lost. Thank you!

**Comment by MeanSquaredError** [comment]
By the way I looked at the fix and it looks good. I was thinking about something similar but sorting updates by pts and then by pts_count, both in increasing order. So for example if these 3 updates were to arrive in this order:

pts=25, pts_count=7
pts=25, pts_count=0
pts=26, pts_count=10

they would be sorted like this:
pts=25, pts_count=0
pts=25, pts_count=7
pts=26, pts_count=10

Seems like it would fix the problem too. However I am not familiar enough with the codebase, so I am not sure if my suggestion is more or less code to implement than the current fix and whether it is reliable enough.
