### ISSUE TITLE
where did FullUser.User go ?

### ISSUE THREAD

**Issue by jackfreed** [gotd/td#694]
After updating from 0.51 to 0.55 i noticed some changes around UsersGetFullUser.

I wanted to access the "**Remaining user info**" of the FullUser as described here: https://core.telegram.org/constructor/userFull but its missing in gotd.

**Comment by tdakkota** [comment]
gotd 0.51.0 uses [Layer 133](https://github.com/gotd/td/blob/v0.51.0/_schema/telegram.tl#L4)
gotd 0.55.0 uses [Layer 137](https://github.com/gotd/td/blob/v0.55.0/_schema/telegram.tl#L5)

`user` field [is gone in Layer 135](https://github.com/gotd/td/commit/4ca0e0787cf20cedb998cd86df15e7d5412e648f#diff-bd3284bac1da8e5f482b9b74928836002e5d06412a276122660d618bf6595cdeL371-R371)

Telegram documentation is outdated. 

You need to make separate `users.getUsers` request to get `User` object.

**Comment by tdakkota** [comment]
I'm going to close this issue because I think it was resolved. Feel free to re-open/create new one if you don't think so.
