### ISSUE TITLE
downlaod photos alway fail: callback: get file: get next chunk: rpcDoRequest: rpc error code 400: FILE_REFERENCE_EXPIRED

### ISSUE THREAD

**Issue by cceessff** [gotd/td#745]
### What version of gotd are you using?

```bash
$ go list -m github.com/gotd/td
github.com/gotd/td v0.56.0

```

### Can this issue be reproduced with the latest version?

I don't know

### What did you do?

```
package main

import (
	"bufio"
	"context"
	"fmt"
	"github.com/gotd/td/session"
	"github.com/gotd/td/telegram/downloader"

	"os"
	"strings"

	"github.com/gotd/td/telegram"
	"github.com/gotd/td/telegram/auth"
	"github.com/gotd/td/tg"
)

func main() {
	client := telegram.NewClient(#####, "##################", telegram.Options{
		SessionStorage: &session.FileStorage{
			Path: "user.json",
		},
	})

	err := client.Run(context.Background(), func(ctx context.Context) error {

		codeFunc := auth.CodeAuthenticatorFunc(func(ctx context.Context, sentCode *tg.AuthSentCode) (string, error) {
			fmt.Print("Enter code: ")
			code, err := bufio.NewReader(os.Stdin).ReadString('\n')
			if err != nil {
				return "", err
			}
			return strings.TrimSpace(code), nil
		})
		authFlow := auth.NewFlow(auth.Constant("*******", "", codeFunc), auth.SendCodeOptions{})

		err := client.Auth().IfNecessary(ctx, authFlow)
		if err != nil {
			return err
		}
		api := client.API()

		request := &tg.ChannelsGetMessagesRequest{
			Channel: &tg.InputChannel{
				ChannelID:  1652331536,
				AccessHash: 8880300310676456582,
			},
			ID: []tg.InputMessageClass{&tg.InputMessageID{ID: 2826}},
		}
		result, err := api.ChannelsGetMessages(ctx, request)
		if err != nil {
			fmt.Println(err.Error())
			return err
		}
		channelMessages:=result.(*tg.MessagesChannelMessages)
		messages := channelMessages.GetMessages()
		downloaderInstance := downloader.NewDownloader()
		for _, message := range messages {
			if message.TypeID() == tg.MessageTypeID {
				msg, ok := message.(*tg.Message)
				if !ok {
					continue
				}
			
				if msg.Media != nil && msg.Media.TypeID() == tg.MessageMediaPhotoTypeID {
					media := msg.Media.(*tg.MessageMediaPhoto)
					photo, ok := media.GetPhoto()
					if !ok {
						continue
					}
					originPhoto := photo.(*tg.Photo)
					_, err = downloaderInstance.Download(client.API(), &tg.InputPhotoFileLocation{
						ID:            originPhoto.GetID(),
						AccessHash:    originPhoto.GetAccessHash(),
						FileReference: originPhoto.GetFileReference(),
					}).ToPath(ctx, fmt.Sprintf("%d.png", originPhoto.GetID()))
					if err!=nil {
						return  err
					}
				}

			}
		}
		return nil
	})
	if err != nil {
		fmt.Println(err.Error())
	}

}

```

### What did you expect to see?

I want to download files

### What did you see instead?

callback: get file: get next chunk: rpcDoRequest: rpc error code 400: FILE_REFERENCE_EXPIRED

### What Go version and environment are you using?

```bash
$ go version
```

<details>
    <summary>
        <code>go env</code> Output
    </summary>
    <br />
    <pre>set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Ms-User\AppData\Local\go-build
set GOENV=C:\Users\Ms-User\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Ms-User\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\devTools\GOPATH;C:\Users\Ms-User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\devTools\GO
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\devTools\GO\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Code\GO\telegram_client\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Ms-User\AppData\Local\Temp\go-build4214324717=/tmp/go-build -gno-re
cord-gcc-switches
</pre>
</details>

**Comment by VladPetriv** [comment]
Are you solved it?

**Comment by cceessff** [comment]
> Are you solved it?

yes ,  I have solved . it is my own fault

**Comment by VladPetriv** [comment]
Can you tell me more about this fail?

> > Are you solved it?
> 
> yes , I have solved . it is my own fault

Can you tell me more about this fail?

**Comment by cceessff** [comment]
> > yes , I have solved . it is my own fault
> 
> Can you tell me more about this fail? Because have the same problem and no idea how to fix it

I do not know what is your problem. But My problem is that I ignored the 'ThumbSize' parameter in "tg.InputPhotoFileLocation".while I add this parameter , and solved it

**Comment by VladPetriv** [comment]
> I do not know what is your problem. But My problem is that I ignored the 'ThumbSize' parameter in "tg.InputPhotoFileLocation".while I add this parameter , and solved it

It's help me too. Thanks)

**Comment by nvtuan305** [comment]
How do you solve it @VladPetriv @cceessff ? I have tried but not working, still get the FILE_REFERENCE_EXPIRED error.

Here is my code. Assuming that `message` is the output of `client.API().MessagesGetHistory` function. Thank for your help.

```golang
photo := message.Media.(*tg.MessageMediaPhoto).Photo.(*tg.Photo)

thumbSize := ""
if len(photo.Sizes) > 1 {
	thumbSize = photo.Sizes[0].String() // 
}

fileLoc := &tg.InputPhotoFileLocation{
	ID:            photo.ID,
	AccessHash:    photo.AccessHash,
	FileReference: photo.GetFileReference(),
	ThumbSize:     thumbSize,
}

mediaDownloader := downloader.NewDownloader()
r, dErr := mediaDownloader.Download(client.API(), fileLoc).
	ToPath(ctx, fmt.Sprintf("%v_%v.png", photo.ID, time.Now().Nanosecond()))

fmt.Println("\nOutput: ", r, dErr)
```

**Comment by msadakov** [comment]
> How do you solve it @VladPetriv @cceessff ? I have tried but not working, still get the FILE_REFERENCE_EXPIRED error.
> 
> Here is my code. Assuming that `message` is the output of `client.API().MessagesGetHistory` function. Thank for your help.
> 
> ```go
> photo := message.Media.(*tg.MessageMediaPhoto).Photo.(*tg.Photo)
> 
> thumbSize := ""
> if len(photo.Sizes) > 1 {
> 	thumbSize = photo.Sizes[0].String() // 
> }
> 
> fileLoc := &tg.InputPhotoFileLocation{
> 	ID:            photo.ID,
> 	AccessHash:    photo.AccessHash,
> 	FileReference: photo.GetFileReference(),
> 	ThumbSize:     thumbSize,
> }
> 
> mediaDownloader := downloader.NewDownloader()
> r, dErr := mediaDownloader.Download(client.API(), fileLoc).
> 	ToPath(ctx, fmt.Sprintf("%v_%v.png", photo.ID, time.Now().Nanosecond()))
> 
> fmt.Println("\nOutput: ", r, dErr) // <nil> get file: get next chunk: rpcDoRequest: rpc error code 400: FILE_REFERENCE_EXPIRED
> ```

```go
ThumbSize:     "y",
```

**Comment by TeaDove** [comment]
@nvtuan305 I have found solution!

In @VladPetriv repository the is [example](https://github.com/VladPetriv/tg_scanner/blob/c4aafea51a9e943167dbb29422a4db286fe6216f/internal/client/message/message.go#L144)

```go
thumbSize := ""
		if len(f.Sizes) > 1 {
			// Lowest (f.Sizes[0]) size has the lowest resolution
			// Highest (f.Sizes[len(f.Sizes)-1]) has the highest resolution
			thumbSize = f.Sizes[len(f.Sizes)-1].GetType()
		}
		input:= &tg.InputPhotoFileLocation{
			ID:            f.ID,
			AccessHash:    f.AccessHash,
			FileReference: f.FileReference,
			ThumbSize:     thumbSize,
		}
```
Just use getType(), not String()
