### ISSUE TITLE
client: PhoneCode missing in AuthSignUpRequest

### ISSUE THREAD

**Issue by Xniveres** [gotd/td#747]
AuthSignUpRequest is missing "PhoneCode",
the official telegram docs are wrong on this as well:

https://core.telegram.org/method/auth.signUp

current struct:

```
type AuthSignUpRequest struct {
	// Phone number in the international format
	PhoneNumber string
	// SMS-message ID
	PhoneCodeHash string
	// New user first name
	FirstName string
	// New user last name
	LastName string
}
```

should be:

```
type AuthSignUpRequest struct {
	// Phone number in the international format
	PhoneNumber string
	// SMS-message ID
	PhoneCodeHash string
        ///Auth Code
	PhoneCode string
	// New user first name
	FirstName string
	// New user last name
	LastName string
}
```

https://core.telegram.org/method/auth.signUp

at the parameter list are 4 parameters, in the example 5.

**Comment by tdakkota** [comment]
Why are you think that `PhoneCode` field is missing?
[There is no such field in TDLib schema.](https://github.com/tdlib/td/blob/43ea7be0fbca64995eca3c902a4c77e6d44c2de2/td/generate/scheme/telegram_api.tl#L1373)

**Comment by ernado** [comment]
```tl
auth.signUp#80eee427 phone_number:string phone_code_hash:string first_name:string last_name:string = auth.Authorization;
```

Probably the example is wrong or outdated, `auth.signUp` has 4 fields in all known schemas.

**Comment by Xniveres** [comment]
> Why are you think that `PhoneCode` field is missing? [There is no such field in TDLib schema.](https://github.com/tdlib/td/blob/43ea7be0fbca64995eca3c902a4c77e6d44c2de2/td/generate/scheme/telegram_api.tl#L1373)

look at the error codes from https://core.telegram.org/method/auth.signUp
PHONE_CODE_EMPTY | phone_code is missing.

you can also validate this issue if you run it in the test network.

**Comment by tdakkota** [comment]
>  but I'm not sure whether it is enabled or not

It doesn't. Issue #554.

**Comment by ernado** [comment]
Pyrogram: https://docs.pyrogram.org/telegram/functions/auth/sign-up#pyrogram.raw.functions.auth.SignUp (4 fields)
Telethon: https://tl.telethon.dev/methods/auth/sign_up.html (4 fields)
Grammers: https://github.com/Lonami/grammers/blob/a0953b22508c97b25ea8c266ba867daf456fef8d/lib/grammers-client/src/client/auth.rs#L464-L478 (4 fields)
Madeline: https://docs.madelineproto.xyz/API_docs/methods/auth.signUp.html (4 fields)
