### ISSUE TITLE
Suggest developing and refining https://github.com/xelaj/mtproto together

### ISSUE THREAD

**Issue by zerobuilder** [gotd/td#785]
Suggest developing and refining https://github.com/xelaj/mtproto together

**Comment by ernado** [comment]
The gotd is superset of xelaj/mtproto, not sure why anybody should develop xelaj/mtproto, it is dead for more than a year.

These PRs are already here from august 2021 from one of (and most experienced) gotd maintainers:
https://github.com/xelaj/mtproto/pull/114
https://github.com/xelaj/mtproto/pull/115

So I suggest archiving xelaj/mtproto and develop gotd instead.
