### ISSUE TITLE
client: How send media

### ISSUE THREAD

**Issue by LazarenkoA** [gotd/td#90]
Hi, please share an example of how to send a media (picture) to a specific recipient?
`tg. Client` has a method `MessagesSendMedia`, it is not clear how it works and whether it works at all (for example, `MessagesSendMessage` does not work)

**Comment by ernado** [comment]
Hi, currently helpers for sending media are not implemented.

I'm planning to start implementing them after we deal with update management https://github.com/gotd/td/issues/91

**Comment by ernado** [comment]
Current solution is to use `tg.Client` directly and follow [Uploading and Downloading Files](https://core.telegram.org/api/files) Telegram documentation.

**Comment by LazarenkoA** [comment]
thanks for the answer

**Comment by ernado** [comment]
@tdakkota implemented upload helpers, now it should be easier to upload media.
