### ISSUE TITLE
Updates Middleware Delays: Extremely Slow Message Re-Fetching Time

### ISSUE THREAD

**Issue by mwein99** [gotd/td#961]
### What version of gotd are you using?

v0.70.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Run the updates example code linked [here](https://github.com/gotd/td/blob/main/examples/updates/main.go)

### What did you expect to see?

Dropped messages should be re-fetched within a couple of seconds, at max
_Delay is calculated as the difference between when the message is received and the `Date` field on the message_

### What did you see instead?

Some dropped messages take up to **10 minutes** to be re-fetched (with no specific log as to why it took this long)

### What Go version and environment are you using?

go1.18.4

**Comment by pyromano** [comment]
Hey, @mwein99. I have also encountered the same behavior. Have you found a solution to the issue?
