### ISSUE TITLE
Websocket Confusion: Gap recovery time

### ISSUE THREAD

**Issue by felipe-linares** [gotd/td#962]
### What version of gotd are you using?

```bash
github.com/gotd/td v0.70.0
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Run over extended periods of time using [updates](https://github.com/gotd/td/blob/main/examples/updates/main.go) example with websocket as the connection type

### What did you expect to see?

Expected low delay and fast messages

### What did you see instead?

When a gap is detected, recovery time takes a whil

### What Go version and environment are you using?

```bash
go version go1.19.2 linux/amd64
```

Hello, we're a bit confused about the functionality of telegram via websockets.

As mentioned in other tickets, there are a lot of features undocumented so it's a bit hard to understand without digging through the code.

After some digging, we realized some messages were getting dropped and not recovered for a while and wanted to make sure we understood the logic/flow correctly via `websockets`.

When a gap is detected, what is the point of the timeout? Often times this timeout can be up to 40+ seconds which causes high delays in messages being recovered. Why not just refetch the channel state and get those messages? 

Also what causes initial gaps in states? Is it just due to random websocket messages being dropped?

**Comment by ernado** [comment]
> what is the point of the timeout
AFAIK it is for case when gap can self-fix via incoming updates that are being received shortly

Personally I've never used websocket, so can't help much with it.

**Comment by felipe-linares** [comment]
Closing this as we realized that the gap and timeout is just part of the telegram schema and is just how their protocol works (I assume to avoid spam while trying to recover gaps in messages).

Unfortunate as it can result in some very long timeouts but have to adhere to the protocol I guess
